version: "3.9"

services:
  app:
    build: ./docker/php
    expose:
      - 9000
    volumes:
      - ./app:/www:cached
    depends_on:
      - db

  web:
    build: ./docker/ngnix
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/www:cached
    depends_on:
      - app

  db:
    build: ./docker/mysql
    expose:
      - 3306
    env_file:
      - ./docker/mysql/db.env
    volumes:
      - db-store:/var/lib/mysql

  mailhog:
    build: ./docker/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    depends_on:
      - web

volumes:
  conf-store:
  db-store:
